component C {

  let max = 10;

  let array = for (i in 0..max) {
    i
  };

  let string_array = ["one", "two", "three", "!"];

  let null_value? = if(false) "something";

  #Template {
    <section>
      <h1>EXCLUSIVE RANGES</h1>

      {"\n"}
      {"\n"}

      0..10
      {for (i in 0..10) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0..0
      {for (i in 0..0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0..1
      {for (i in 0..1) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0..-1
      {for (i in 0..-1) { <div class="item">{i}</div> {"\n"} }}

      -10..10
      {for (i in -10..10) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      10..0
      {for (i in 10..0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      10..0 reverse
      {for (i in reverse 10..0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}
      {"\n"}

      <h1>INCLUSIVE RANGES</h1>
      0...10
      {for (i in 0...10) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0...0
      {for (i in 0...0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0...1
      {for (i in 0...1) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0...-1
      {for (i in 0...-1) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      -10...10
      {for (i in -10...10) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      10...0
      {for (i in 10...0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      10...0 reverse
      {for (i in reverse 10...0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      <h1>ITERABLES</h1>

      {"\n"}
      {"\n"}

      array
      {for (i in array) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      array reverse
      {for (i in reverse array) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      string
      {for (c in "String!") { <div class="item">{c}</div> {"\n"} }}

      {"\n"}

      string reverse
      {for (c in reverse "String!") { <div class="item">{c}</div> {"\n"} }}

      {"\n"}

      string array
      {for (s in string_array) { <div class="item">{s}</div> {"\n"} }}

      {"\n"}

      null value
      {for (s in null_value) { <div class="item">{s}</div> {"\n"} }}
    </section>
  }
}
