component C {

  let max = 10;

  let array = for (i in 0 to max) {
    i
  };

  #Template {
    <section>
      0 to 10
      {for (i in 0 to 10) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      0 to 0
      {for (i in 0 to 0) { <div class="item">{i}</div> {"\n"} }}

      {"\n"}

      -10 to 10
      {for (i in -10 to 10) { <div class="item">{i}</div> {"\n"} }}

    </section>
  }
}
