component Section(
  label: "Section",
  icon: "/images/icons/group.svg",
  group: "Structure",
) {

  content = "Hello, World!";

  @Template {
    <section class="Section">
      <div />
      {if (intro) {
        foobar = "foo";
        if (foobar) {
          <div />
        } else {
          barfoo = "3";
          <span />
        }
      }}
      <div class="Section-content">
        {content}
      </div>
      <div class="Section-footer">
        Lorem Ipsum dolor sit amet!!
      </div>
    </section>
  }
}
