// Generated by Melange

import * as Pinc_Tags from "./Pinc_Tags.js";
import * as StringMap from "./StringMap.js";
import * as Pinc_Lexer from "./Pinc_Lexer.js";
import * as Pinc_Token from "./Pinc_Token.js";
import * as Pinc_Parser from "./Pinc_Parser.js";
import * as Pinc_Interpreter from "./Pinc_Interpreter.js";

var Tags = Pinc_Tags;

var Token = Pinc_Token;

var Lexer = Pinc_Lexer;

var Parser = Pinc_Parser;

var Types = {};

var Interpreter = {
  Value: Pinc_Interpreter.Value,
  State: Pinc_Interpreter.State,
  eval_meta: Pinc_Interpreter.eval_meta,
  $$eval: Pinc_Interpreter.$$eval,
  from_source: Pinc_Interpreter.from_source,
  Types: Types
};

var StringMap$1 = StringMap;

export {
  Tags ,
  Token ,
  Lexer ,
  Parser ,
  Interpreter ,
  StringMap$1 as StringMap,
}
/* Pinc_Tags Not a pure module */
