// Generated by Melange

import * as Int from "bs-platform/lib/es6/int.js";
import * as Bool from "bs-platform/lib/es6/bool.js";
import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Float from "bs-platform/lib/es6/float.js";
import * as $$Buffer from "bs-platform/lib/es6/buffer.js";
import * as Either from "bs-platform/lib/es6/either.js";
import * as $$Option from "bs-platform/lib/es6/option.js";
import * as Stdlib from "bs-platform/lib/es6/stdlib.js";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Pinc_Ast from "./Pinc_Ast.js";
import * as Pinc_HTML from "./Pinc_HTML.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Pinc_Parser from "./Pinc_Parser.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";

var Loop_Break = /* @__PURE__ */Caml_exceptions.create("Pinc_Interpreter.Loop_Break");

var Loop_Continue = /* @__PURE__ */Caml_exceptions.create("Pinc_Interpreter.Loop_Continue");

function $$null(param) {
  return /* Null */0;
}

function of_string(s) {
  return {
          TAG: /* String */0,
          _0: s
        };
}

function of_bool(b) {
  return {
          TAG: /* Bool */3,
          _0: b
        };
}

function of_int(i) {
  return {
          TAG: /* Int */1,
          _0: i
        };
}

function of_float(f) {
  return {
          TAG: /* Float */2,
          _0: f
        };
}

function of_list(l) {
  return {
          TAG: /* Array */4,
          _0: $$Array.of_list(l)
        };
}

function of_string_map(m) {
  return {
          TAG: /* Record */5,
          _0: m
        };
}

function make_component(render, tag, attributes, children) {
  return {
          TAG: /* TemplateNode */8,
          _0: {
            NAME: "Component",
            VAL: render
          },
          _1: tag,
          _2: attributes,
          _3: children,
          _4: false
        };
}

function to_string(_s) {
  while(true) {
    var s = _s;
    if (typeof s === "number") {
      return "";
    }
    switch (s.TAG | 0) {
      case /* String */0 :
          return s._0;
      case /* Int */1 :
          return String(s._0);
      case /* Float */2 :
          var f = s._0;
          if (Float.is_integer(f)) {
            return String(f | 0);
          } else {
            return Stdlib.string_of_float(f);
          }
      case /* Bool */3 :
          if (s._0) {
            return "true";
          } else {
            return "false";
          }
      case /* Array */4 :
          var buf = $$Buffer.create(200);
          $$Array.iteri((function(buf){
              return function (i, it) {
                if (i !== 0) {
                  $$Buffer.add_char(buf, /* '\n' */10);
                }
                return $$Buffer.add_string(buf, to_string(it));
              }
              }(buf)), s._0);
          return $$Buffer.contents(buf);
      case /* Record */5 :
          var b = $$Buffer.create(1024);
          Curry._2(Pinc_Ast.StringMap.iter, (function(b){
              return function (_key, value) {
                $$Buffer.add_string(b, to_string(value));
                return $$Buffer.add_char(b, /* '\n' */10);
              }
              }(b)), s._0);
          return $$Buffer.contents(b);
      case /* Function */6 :
      case /* DefinitionInfo */7 :
          return "";
      case /* TemplateNode */8 :
          var match = s._0;
          if (typeof match === "string") {
            var attributes = s._2;
            var tag = s._1;
            var buf$1 = $$Buffer.create(128);
            $$Buffer.add_char(buf$1, /* '<' */60);
            $$Buffer.add_string(buf$1, tag);
            if (!Curry._1(Pinc_Ast.StringMap.is_empty, attributes)) {
              Curry._2(Pinc_Ast.StringMap.iter, (function(buf$1){
                  return function (key, value) {
                    if (typeof value === "number") {
                      return ;
                    } else {
                      $$Buffer.add_char(buf$1, /* ' ' */32);
                      $$Buffer.add_string(buf$1, key);
                      $$Buffer.add_char(buf$1, /* '=' */61);
                      $$Buffer.add_char(buf$1, /* '"' */34);
                      $$Buffer.add_string(buf$1, to_string(value));
                      return $$Buffer.add_char(buf$1, /* '"' */34);
                    }
                  }
                  }(buf$1)), attributes);
            }
            if (s._4 && Pinc_HTML.is_void_el(tag)) {
              $$Buffer.add_string(buf$1, " />");
            } else {
              $$Buffer.add_char(buf$1, /* '>' */62);
              List.iter((function(buf$1){
                  return function (child) {
                    return $$Buffer.add_string(buf$1, to_string(child));
                  }
                  }(buf$1)), s._3);
              $$Buffer.add_char(buf$1, /* '<' */60);
              $$Buffer.add_char(buf$1, /* '/' */47);
              $$Buffer.add_string(buf$1, tag);
              $$Buffer.add_char(buf$1, /* '>' */62);
            }
            return $$Buffer.contents(buf$1);
          }
          var attributes$1 = s._2;
          var models = (function(attributes$1){
          return function models(s) {
            return Curry._2(Pinc_Ast.StringMap.find_opt, s, attributes$1);
          }
          }(attributes$1));
          _s = Curry._2(match.VAL, models, s._3);
          continue ;
      
    }
  };
}

function is_true(b) {
  if (typeof b === "number") {
    return false;
  }
  switch (b.TAG | 0) {
    case /* String */0 :
        return $$String.trim(b._0).length !== 0;
    case /* Bool */3 :
        return b._0;
    case /* Array */4 :
        if (b._0.length) {
          return true;
        } else {
          return false;
        }
    case /* Record */5 :
        return !Curry._1(Pinc_Ast.StringMap.is_empty, b._0);
    case /* DefinitionInfo */7 :
        return b._0.exists;
    default:
      return true;
  }
}

function equal(a, b) {
  if (typeof a === "number") {
    if (typeof b === "number") {
      return true;
    } else {
      return false;
    }
  }
  switch (a.TAG | 0) {
    case /* String */0 :
        if (typeof b === "number" || b.TAG !== /* String */0) {
          return false;
        } else {
          return $$String.equal(a._0, b._0);
        }
    case /* Int */1 :
        var a$1 = a._0;
        if (typeof b === "number") {
          return false;
        }
        switch (b.TAG | 0) {
          case /* Int */1 :
              return a$1 === b._0;
          case /* Float */2 :
              return a$1 === b._0;
          default:
            return false;
        }
    case /* Float */2 :
        var a$2 = a._0;
        if (typeof b === "number") {
          return false;
        }
        switch (b.TAG | 0) {
          case /* Int */1 :
              return a$2 === b._0;
          case /* Float */2 :
              return a$2 === b._0;
          default:
            return false;
        }
    case /* Bool */3 :
        if (typeof b === "number" || b.TAG !== /* Bool */3) {
          return false;
        } else {
          return a._0 === b._0;
        }
    case /* Array */4 :
        if (typeof b === "number" || b.TAG !== /* Array */4) {
          return false;
        } else {
          return Caml_obj.caml_equal(a._0, b._0);
        }
    case /* Record */5 :
        if (typeof b === "number" || b.TAG !== /* Record */5) {
          return false;
        } else {
          return Curry._3(Pinc_Ast.StringMap.equal, equal, a._0, b._0);
        }
    case /* Function */6 :
        return false;
    case /* DefinitionInfo */7 :
        if (typeof b === "number" || b.TAG !== /* DefinitionInfo */7) {
          return false;
        } else {
          return $$String.equal(a._0.name, b._0.name);
        }
    case /* TemplateNode */8 :
        if (typeof b === "number" || !(b.TAG === /* TemplateNode */8 && Caml_obj.caml_equal(a._0, b._0) && a._1 === b._1 && a._4 === b._4 && Curry._3(Pinc_Ast.StringMap.equal, equal, a._2, b._2))) {
          return false;
        } else {
          return Caml_obj.caml_equal(a._3, b._3);
        }
    
  }
}

function compare(a, b) {
  if (typeof a === "number") {
    if (typeof b === "number") {
      return 0;
    }
    
  } else {
    switch (a.TAG | 0) {
      case /* String */0 :
          if (typeof b !== "number" && b.TAG === /* String */0) {
            return $$String.compare(a._0, b._0);
          }
          break;
      case /* Int */1 :
          var a$1 = a._0;
          if (typeof b !== "number") {
            switch (b.TAG | 0) {
              case /* Int */1 :
                  return Int.compare(a$1, b._0);
              case /* Float */2 :
                  return Float.compare(a$1, b._0);
              default:
                
            }
          }
          break;
      case /* Float */2 :
          var a$2 = a._0;
          if (typeof b !== "number") {
            switch (b.TAG | 0) {
              case /* Int */1 :
                  return Float.compare(a$2, b._0);
              case /* Float */2 :
                  return Float.compare(a$2, b._0);
              default:
                
            }
          }
          break;
      case /* Bool */3 :
          if (typeof b !== "number" && b.TAG === /* Bool */3) {
            return Bool.compare(a._0, b._0);
          }
          break;
      case /* Array */4 :
          if (typeof b !== "number" && b.TAG === /* Array */4) {
            return Int.compare(a._0.length, b._0.length);
          }
          break;
      case /* Record */5 :
          if (typeof b !== "number" && b.TAG === /* Record */5) {
            return Curry._3(Pinc_Ast.StringMap.compare, compare, a._0, b._0);
          }
          break;
      case /* Function */6 :
          if (typeof b !== "number" && b.TAG === /* Function */6) {
            return 0;
          }
          break;
      case /* DefinitionInfo */7 :
          if (typeof b !== "number" && b.TAG === /* DefinitionInfo */7) {
            return 0;
          }
          break;
      case /* TemplateNode */8 :
          if (typeof b !== "number" && b.TAG === /* TemplateNode */8) {
            return 0;
          }
          break;
      
    }
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "Pinc_Interpreter.ml",
          214,
          11
        ],
        Error: new Error()
      };
}

function make(modelsOpt, slotted_children, contextOpt, declarations) {
  var models = modelsOpt !== undefined ? modelsOpt : (function (param) {
        
      });
  var context = contextOpt !== undefined ? Caml_option.valFromOption(contextOpt) : Pinc_Ast.StringMap.empty;
  return {
          binding_identifier: undefined,
          models: models,
          slotted_children: slotted_children,
          declarations: declarations,
          context: context,
          output: /* Null */0,
          environment: {
            scope: /* [] */0
          }
        };
}

function add_context(name, value, t) {
  var context = Curry._3(Pinc_Ast.StringMap.add, name, value, t.context);
  return {
          binding_identifier: t.binding_identifier,
          models: t.models,
          slotted_children: t.slotted_children,
          declarations: t.declarations,
          context: context,
          output: t.output,
          environment: t.environment
        };
}

function get_context(name, t) {
  return Curry._2(Pinc_Ast.StringMap.find_opt, name, t.context);
}

function add_scope(t) {
  var environment = {
    scope: {
      hd: /* [] */0,
      tl: t.environment.scope
    }
  };
  return {
          binding_identifier: t.binding_identifier,
          models: t.models,
          slotted_children: t.slotted_children,
          declarations: t.declarations,
          context: t.context,
          output: t.output,
          environment: environment
        };
}

function add_value_to_scope(ident, value, is_optional, is_mutable, t) {
  var update_scope = function (t) {
    var match = t.environment.scope;
    if (match) {
      return {
              hd: {
                hd: [
                  ident,
                  {
                    is_mutable: is_mutable,
                    is_optional: is_optional,
                    value: value
                  }
                ],
                tl: match.hd
              },
              tl: match.tl
            };
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "Pinc_Interpreter.ml",
            319,
            14
          ],
          Error: new Error()
        };
  };
  var environment = {
    scope: update_scope(t)
  };
  return {
          binding_identifier: t.binding_identifier,
          models: t.models,
          slotted_children: t.slotted_children,
          declarations: t.declarations,
          context: t.context,
          output: t.output,
          environment: environment
        };
}

function update_value_in_scope(ident, value, t) {
  var updated = {
    contents: false
  };
  var update_scope = function (state) {
    return List.map((function (scope) {
                  if (updated.contents) {
                    return scope;
                  } else {
                    return List.map((function (v) {
                                  var binding = v[1];
                                  var key = v[0];
                                  if (!updated.contents && key === ident && binding.is_mutable) {
                                    updated.contents = true;
                                    return [
                                            key,
                                            {
                                              is_mutable: binding.is_mutable,
                                              is_optional: binding.is_optional,
                                              value: value
                                            }
                                          ];
                                  }
                                  var match = binding.value;
                                  if (typeof match === "number") {
                                    return v;
                                  }
                                  if (match.TAG !== /* Function */6) {
                                    return v;
                                  }
                                  if (updated.contents) {
                                    return v;
                                  }
                                  var fn_state = match.state;
                                  fn_state.environment.scope = update_scope(fn_state);
                                  return [
                                          key,
                                          {
                                            is_mutable: binding.is_mutable,
                                            is_optional: binding.is_optional,
                                            value: {
                                              TAG: /* Function */6,
                                              parameters: match.parameters,
                                              state: fn_state,
                                              exec: match.exec
                                            }
                                          }
                                        ];
                                }), scope);
                  }
                }), state.environment.scope);
  };
  t.environment.scope = update_scope(t);
}

function get_value_from_scope(ident, t) {
  return List.find_map((function (param) {
                return List.assoc_opt(ident, param);
              }), t.environment.scope);
}

function get_output(t) {
  return t.output;
}

function add_output(output, t) {
  return {
          binding_identifier: t.binding_identifier,
          models: t.models,
          slotted_children: t.slotted_children,
          declarations: t.declarations,
          context: t.context,
          output: output,
          environment: t.environment
        };
}

function get_bindings(t) {
  return List.hd(t.environment.scope);
}

function eval_statement(state, expression) {
  if (typeof expression === "number") {
    if (expression === /* BreakStatement */0) {
      throw {
            RE_EXN_ID: Loop_Break,
            Error: new Error()
          };
    }
    throw {
          RE_EXN_ID: Loop_Continue,
          Error: new Error()
        };
  } else {
    switch (expression.TAG | 0) {
      case /* OptionalMutableLetStatement */0 :
          return eval_let(state, expression._0._0, true, true, expression._1);
      case /* OptionalLetStatement */1 :
          return eval_let(state, expression._0._0, false, true, expression._1);
      case /* MutableLetStatement */2 :
          return eval_let(state, expression._0._0, true, false, expression._1);
      case /* LetStatement */3 :
          return eval_let(state, expression._0._0, false, false, expression._1);
      case /* MutationStatement */4 :
          var ident = expression._0._0;
          var expression$1 = expression._1;
          var current_binding = get_value_from_scope(ident, state);
          if (current_binding === undefined) {
            return Stdlib.failwith("Trying to update a variable, which does not exist in the current scope.");
          }
          if (!current_binding.is_mutable) {
            return Stdlib.failwith("Trying to update a non mutable variable.");
          }
          var output = eval_expression({
                binding_identifier: ident,
                models: state.models,
                slotted_children: state.slotted_children,
                declarations: state.declarations,
                context: state.context,
                output: state.output,
                environment: state.environment
              }, expression$1);
          var value = output.output;
          if (typeof value === "number" && !current_binding.is_optional) {
            Stdlib.failwith("identifier " + (ident + " is not marked as nullable, but was tried to be updated with a null value."));
          } else {
            update_value_in_scope(ident, value, state);
          }
          return add_output(/* Null */0, state);
      case /* ExpressionStatement */5 :
          return eval_expression(state, expression._0);
      
    }
  }
}

function eval_expression(state, i) {
  switch (i.TAG | 0) {
    case /* String */0 :
        var template = i._0;
        return add_output({
                    TAG: /* String */0,
                    _0: $$String.concat("", List.map((function (s) {
                                if (s.TAG === /* StringInterpolation */0) {
                                  return to_string(eval_expression(state, s._0).output);
                                } else {
                                  return s._0;
                                }
                              }), template))
                  }, state);
    case /* Int */1 :
        return add_output({
                    TAG: /* Int */1,
                    _0: i._0
                  }, state);
    case /* Float */2 :
        var f = i._0;
        if (Float.is_integer(f)) {
          return add_output({
                      TAG: /* Int */1,
                      _0: f | 0
                    }, state);
        } else {
          return add_output({
                      TAG: /* Float */2,
                      _0: f
                    }, state);
        }
    case /* Bool */3 :
        return add_output({
                    TAG: /* Bool */3,
                    _0: i._0
                  }, state);
    case /* Array */4 :
        return add_output({
                    TAG: /* Array */4,
                    _0: $$Array.map((function (it) {
                            return eval_expression(state, it).output;
                          }), i._0)
                  }, state);
    case /* Record */5 :
        return add_output({
                    TAG: /* Record */5,
                    _0: Curry._2(Pinc_Ast.StringMap.mapi, (function (ident, param) {
                            var value = eval_expression({
                                  binding_identifier: ident,
                                  models: state.models,
                                  slotted_children: state.slotted_children,
                                  declarations: state.declarations,
                                  context: state.context,
                                  output: state.output,
                                  environment: state.environment
                                }, param[1]).output;
                            if (typeof value === "number" && !param[0]) {
                              return Stdlib.failwith("identifier " + (ident + " is not marked as nullable, but was given a null value."));
                            } else {
                              return value;
                            }
                          }), i._0)
                  }, state);
    case /* Function */6 :
        var parameters = i._0;
        var body = i._1;
        var ident = state.binding_identifier;
        var self = {
          contents: /* Null */0
        };
        var exec = function ($$arguments, state, param) {
          var state$1 = ident !== undefined ? add_value_to_scope(ident, self.contents, false, false, state) : state;
          var state$2 = Curry._3(Pinc_Ast.StringMap.fold, (function (ident, value) {
                  return function (param) {
                    return add_value_to_scope(ident, value, false, false, param);
                  };
                }), $$arguments, add_scope(state$1));
          return eval_expression(state$2, body).output;
        };
        var fn = {
          TAG: /* Function */6,
          parameters: parameters,
          state: state,
          exec: exec
        };
        $$Option.iter((function (ident) {
                var is_optional = false;
                var is_mutable = false;
                var update_scope = function (state) {
                  return List.map((function (param) {
                                return List.map((function (v) {
                                              var binding = v[1];
                                              var match = binding.value;
                                              if (typeof match === "number") {
                                                return v;
                                              }
                                              if (match.TAG !== /* Function */6) {
                                                return v;
                                              }
                                              var new_state = add_value_to_scope(ident, fn, is_optional, is_mutable, match.state);
                                              return [
                                                      v[0],
                                                      {
                                                        is_mutable: binding.is_mutable,
                                                        is_optional: binding.is_optional,
                                                        value: {
                                                          TAG: /* Function */6,
                                                          parameters: match.parameters,
                                                          state: new_state,
                                                          exec: match.exec
                                                        }
                                                      }
                                                    ];
                                            }), param);
                              }), state.environment.scope);
                };
                state.environment.scope = update_scope(state);
              }), ident);
        self.contents = fn;
        return add_output(fn, state);
    case /* FunctionCall */7 :
        return eval_function_call(state, i._1, i._0);
    case /* UppercaseIdentifierExpression */8 :
        var id = i._0._0;
        var value = Curry._2(Pinc_Ast.StringMap.find_opt, id, state.declarations);
        return add_output({
                    TAG: /* DefinitionInfo */7,
                    _0: {
                      name: id,
                      exists: $$Option.is_some(value),
                      negated: false
                    }
                  }, state);
    case /* LowercaseIdentifierExpression */9 :
        var ident$1 = i._0._0;
        var param = get_value_from_scope(ident$1, state);
        if (param !== undefined) {
          return add_output(param.value, state);
        } else {
          return Stdlib.failwith("Unbound identifier `" + (ident$1 + "`"));
        }
    case /* TagExpression */10 :
        return eval_tag(undefined, state, i._0);
    case /* ForInExpression */11 :
        var index_ident = i.index;
        var ident$2 = i.iterator._0;
        var reverse = i.reverse;
        var iterable = i.iterable;
        var body$1 = i.body;
        var make_rev = function (array) {
          $$Array.stable_sort((function (param, param$1) {
                  return 1;
                }), array);
          return array;
        };
        var iterable$1 = eval_expression(state, iterable).output;
        var maybe_rev = reverse ? make_rev : (function (arr) {
              return arr;
            });
        var index = {
          contents: -1
        };
        var loop = function (_acc, _param) {
          while(true) {
            var param = _param;
            var acc = _acc;
            if (!param) {
              return List.rev(acc);
            }
            var tl = param.tl;
            index.contents = index.contents + 1 | 0;
            var state$1 = add_value_to_scope(ident$2, param.hd, false, false, state);
            var state$2 = index_ident !== undefined ? add_value_to_scope(index_ident._0, {
                    TAG: /* Int */1,
                    _0: index.contents
                  }, false, false, state$1) : state$1;
            var v;
            try {
              v = eval_statement(state$2, body$1);
            }
            catch (raw_exn){
              var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
              if (exn.RE_EXN_ID === Loop_Continue) {
                _param = tl;
                continue ;
              }
              if (exn.RE_EXN_ID === Loop_Break) {
                return List.rev(acc);
              }
              throw exn;
            }
            _param = tl;
            _acc = {
              hd: v.output,
              tl: acc
            };
            continue ;
          };
        };
        if (typeof iterable$1 === "number") {
          return add_output(/* Null */0, state);
        }
        switch (iterable$1.TAG | 0) {
          case /* String */0 :
              var res = $$Array.of_list(loop(/* [] */0, $$Array.to_list($$Array.map((function (c) {
                                  return {
                                          TAG: /* String */0,
                                          _0: $$String.make(1, c)
                                        };
                                }), Curry._1(maybe_rev, $$Array.of_seq($$String.to_seq(iterable$1._0)))))));
              return add_output({
                          TAG: /* Array */4,
                          _0: res
                        }, state);
          case /* Int */1 :
              return Stdlib.failwith("Cannot iterate over int value");
          case /* Float */2 :
              return Stdlib.failwith("Cannot iterate over float value");
          case /* Bool */3 :
              return Stdlib.failwith("Cannot iterate over boolean value");
          case /* Array */4 :
              var res$1 = $$Array.of_list(loop(/* [] */0, $$Array.to_list(Curry._1(maybe_rev, iterable$1._0))));
              return add_output({
                          TAG: /* Array */4,
                          _0: res$1
                        }, state);
          case /* Record */5 :
              return Stdlib.failwith("Cannot iterate over record value");
          case /* Function */6 :
              return Stdlib.failwith("Cannot iterate over function");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("Cannot iterate over definition info");
          case /* TemplateNode */8 :
              return Stdlib.failwith("Cannot iterate over template node");
          
        }
    case /* TemplateExpression */12 :
        return add_output({
                    TAG: /* Array */4,
                    _0: $$Array.of_list(List.map((function (it) {
                                return eval_template(state, it).output;
                              }), i._0))
                  }, state);
    case /* BlockExpression */13 :
        return eval_block(state, i._0);
    case /* ConditionalExpression */14 :
        var condition = i.condition;
        var alternate = i.alternate;
        var consequent = i.consequent;
        var condition_matches = is_true(eval_expression(state, condition).output);
        if (condition_matches) {
          return eval_statement(state, consequent);
        } else if (alternate !== undefined) {
          return eval_statement(state, alternate);
        } else {
          return add_output(/* Null */0, state);
        }
    case /* UnaryExpression */15 :
        if (i._0) {
          var expression = i._1;
          var info = eval_expression(state, expression).output;
          if (typeof info === "number") {
            return add_output({
                        TAG: /* Bool */3,
                        _0: !is_true(info)
                      }, state);
          }
          if (info.TAG !== /* DefinitionInfo */7) {
            return add_output({
                        TAG: /* Bool */3,
                        _0: !is_true(info)
                      }, state);
          }
          var info$1 = info._0;
          return add_output({
                      TAG: /* DefinitionInfo */7,
                      _0: {
                        name: info$1.name,
                        exists: info$1.exists,
                        negated: !info$1.negated
                      }
                    }, state);
        } else {
          var expression$1 = i._1;
          var i$1 = eval_expression(state, expression$1).output;
          if (typeof i$1 === "number") {
            return Stdlib.failwith("Invalid usage of unary `-` operator. You are only able to negate integers or floats.");
          }
          switch (i$1.TAG | 0) {
            case /* Int */1 :
                return add_output({
                            TAG: /* Int */1,
                            _0: -i$1._0 | 0
                          }, state);
            case /* Float */2 :
                return add_output({
                            TAG: /* Float */2,
                            _0: -i$1._0
                          }, state);
            default:
              return Stdlib.failwith("Invalid usage of unary `-` operator. You are only able to negate integers or floats.");
          }
        }
    case /* BinaryExpression */16 :
        var left = i._0;
        switch (i._1) {
          case /* EQUAL */0 :
              var right = i._2;
              var a = eval_expression(state, left).output;
              var b = eval_expression(state, right).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: equal(a, b)
                        }, state);
          case /* NOT_EQUAL */1 :
              var right$1 = i._2;
              var a$1 = eval_expression(state, left).output;
              var b$1 = eval_expression(state, right$1).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: !equal(a$1, b$1)
                        }, state);
          case /* GREATER */2 :
              var right$2 = i._2;
              var a$2 = eval_expression(state, left).output;
              var b$2 = eval_expression(state, right$2).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: compare(a$2, b$2) > 0
                        }, state);
          case /* GREATER_EQUAL */3 :
              var right$3 = i._2;
              var a$3 = eval_expression(state, left).output;
              var b$3 = eval_expression(state, right$3).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: compare(a$3, b$3) >= 0
                        }, state);
          case /* LESS */4 :
              var right$4 = i._2;
              var a$4 = eval_expression(state, left).output;
              var b$4 = eval_expression(state, right$4).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: compare(a$4, b$4) < 0
                        }, state);
          case /* LESS_EQUAL */5 :
              var right$5 = i._2;
              var a$5 = eval_expression(state, left).output;
              var b$5 = eval_expression(state, right$5).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: compare(a$5, b$5) <= 0
                        }, state);
          case /* PLUS */6 :
              var right$6 = i._2;
              var a$6 = eval_expression(state, left).output;
              var b$6 = eval_expression(state, right$6).output;
              if (typeof a$6 === "number") {
                return Stdlib.failwith("Trying to add non numeric literals.");
              }
              switch (a$6.TAG | 0) {
                case /* Int */1 :
                    var a$7 = a$6._0;
                    if (typeof b$6 === "number") {
                      return Stdlib.failwith("Trying to add non numeric literals.");
                    }
                    switch (b$6.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Int */1,
                                      _0: a$7 + b$6._0 | 0
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$7 + b$6._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to add non numeric literals.");
                    }
                case /* Float */2 :
                    var a$8 = a$6._0;
                    if (typeof b$6 === "number") {
                      return Stdlib.failwith("Trying to add non numeric literals.");
                    }
                    switch (b$6.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$8 + b$6._0
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$8 + b$6._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to add non numeric literals.");
                    }
                default:
                  return Stdlib.failwith("Trying to add non numeric literals.");
              }
          case /* MINUS */7 :
              var right$7 = i._2;
              var a$9 = eval_expression(state, left).output;
              var b$7 = eval_expression(state, right$7).output;
              if (typeof a$9 === "number") {
                return Stdlib.failwith("Trying to subtract non numeric literals.");
              }
              switch (a$9.TAG | 0) {
                case /* Int */1 :
                    var a$10 = a$9._0;
                    if (typeof b$7 === "number") {
                      return Stdlib.failwith("Trying to subtract non numeric literals.");
                    }
                    switch (b$7.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Int */1,
                                      _0: a$10 - b$7._0 | 0
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$10 - b$7._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to subtract non numeric literals.");
                    }
                case /* Float */2 :
                    var a$11 = a$9._0;
                    if (typeof b$7 === "number") {
                      return Stdlib.failwith("Trying to subtract non numeric literals.");
                    }
                    switch (b$7.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$11 - b$7._0
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$11 - b$7._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to subtract non numeric literals.");
                    }
                default:
                  return Stdlib.failwith("Trying to subtract non numeric literals.");
              }
          case /* TIMES */8 :
              var right$8 = i._2;
              var a$12 = eval_expression(state, left).output;
              var b$8 = eval_expression(state, right$8).output;
              if (typeof a$12 === "number") {
                return Stdlib.failwith("Trying to multiply non numeric literals.");
              }
              switch (a$12.TAG | 0) {
                case /* Int */1 :
                    var a$13 = a$12._0;
                    if (typeof b$8 === "number") {
                      return Stdlib.failwith("Trying to multiply non numeric literals.");
                    }
                    switch (b$8.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Int */1,
                                      _0: Math.imul(a$13, b$8._0)
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$13 * b$8._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to multiply non numeric literals.");
                    }
                case /* Float */2 :
                    var a$14 = a$12._0;
                    if (typeof b$8 === "number") {
                      return Stdlib.failwith("Trying to multiply non numeric literals.");
                    }
                    switch (b$8.TAG | 0) {
                      case /* Int */1 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$14 * b$8._0
                                    }, state);
                      case /* Float */2 :
                          return add_output({
                                      TAG: /* Float */2,
                                      _0: a$14 * b$8._0
                                    }, state);
                      default:
                        return Stdlib.failwith("Trying to multiply non numeric literals.");
                    }
                default:
                  return Stdlib.failwith("Trying to multiply non numeric literals.");
              }
          case /* DIV */9 :
              var right$9 = i._2;
              var a$15 = eval_expression(state, left).output;
              var b$9 = eval_expression(state, right$9).output;
              var r;
              if (typeof a$15 === "number") {
                r = Stdlib.failwith("Trying to divide non numeric literals.");
              } else {
                switch (a$15.TAG | 0) {
                  case /* Int */1 :
                      var a$16 = a$15._0;
                      if (typeof b$9 === "number") {
                        r = Stdlib.failwith("Trying to divide non numeric literals.");
                      } else {
                        switch (b$9.TAG | 0) {
                          case /* Int */1 :
                              var b$10 = b$9._0;
                              r = b$10 !== 0 ? a$16 / b$10 : Stdlib.failwith("Trying to divide by 0");
                              break;
                          case /* Float */2 :
                              var b$11 = b$9._0;
                              r = b$11 !== 0 ? a$16 / b$11 : Stdlib.failwith("Trying to divide by 0");
                              break;
                          default:
                            r = Stdlib.failwith("Trying to divide non numeric literals.");
                        }
                      }
                      break;
                  case /* Float */2 :
                      var a$17 = a$15._0;
                      if (typeof b$9 === "number") {
                        r = Stdlib.failwith("Trying to divide non numeric literals.");
                      } else {
                        switch (b$9.TAG | 0) {
                          case /* Int */1 :
                              var b$12 = b$9._0;
                              r = b$12 !== 0 ? a$17 / b$12 : Stdlib.failwith("Trying to divide by 0");
                              break;
                          case /* Float */2 :
                              var b$13 = b$9._0;
                              r = b$13 !== 0 ? a$17 / b$13 : Stdlib.failwith("Trying to divide by 0");
                              break;
                          default:
                            r = Stdlib.failwith("Trying to divide non numeric literals.");
                        }
                      }
                      break;
                  default:
                    r = Stdlib.failwith("Trying to divide non numeric literals.");
                }
              }
              if (Float.is_integer(r)) {
                return add_output({
                            TAG: /* Int */1,
                            _0: r | 0
                          }, state);
              } else {
                return add_output({
                            TAG: /* Float */2,
                            _0: r
                          }, state);
              }
          case /* POW */10 :
              var right$10 = i._2;
              var a$18 = eval_expression(state, left).output;
              var b$14 = eval_expression(state, right$10).output;
              var r$1;
              if (typeof a$18 === "number") {
                r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
              } else {
                switch (a$18.TAG | 0) {
                  case /* Int */1 :
                      var a$19 = a$18._0;
                      if (typeof b$14 === "number") {
                        r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
                      } else {
                        switch (b$14.TAG | 0) {
                          case /* Int */1 :
                              r$1 = Math.pow(a$19, b$14._0);
                              break;
                          case /* Float */2 :
                              r$1 = Math.pow(a$19, b$14._0);
                              break;
                          default:
                            r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
                        }
                      }
                      break;
                  case /* Float */2 :
                      var a$20 = a$18._0;
                      if (typeof b$14 === "number") {
                        r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
                      } else {
                        switch (b$14.TAG | 0) {
                          case /* Int */1 :
                              r$1 = Math.pow(a$20, b$14._0);
                              break;
                          case /* Float */2 :
                              r$1 = Math.pow(a$20, b$14._0);
                              break;
                          default:
                            r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
                        }
                      }
                      break;
                  default:
                    r$1 = Stdlib.failwith("Trying to raise non numeric literals.");
                }
              }
              if (Float.is_integer(r$1)) {
                return add_output({
                            TAG: /* Int */1,
                            _0: r$1 | 0
                          }, state);
              } else {
                return add_output({
                            TAG: /* Float */2,
                            _0: r$1
                          }, state);
              }
          case /* MODULO */11 :
              var right$11 = i._2;
              var a$21 = eval_expression(state, left).output;
              var b$15 = eval_expression(state, right$11).output;
              var r$2;
              if (typeof a$21 === "number") {
                r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
              } else {
                switch (a$21.TAG | 0) {
                  case /* Int */1 :
                      var a$22 = a$21._0;
                      if (typeof b$15 === "number") {
                        r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
                      } else {
                        switch (b$15.TAG | 0) {
                          case /* Int */1 :
                              var b$16 = b$15._0;
                              r$2 = b$16 !== 0 ? Caml_int32.mod_(a$22, b$16) : Stdlib.failwith("Trying to modulo with 0 on right hand side.");
                              break;
                          case /* Float */2 :
                              var b$17 = b$15._0;
                              r$2 = b$17 !== 0 ? Caml_int32.mod_(a$22, b$17 | 0) : Stdlib.failwith("Trying to modulo with 0 on right hand side.");
                              break;
                          default:
                            r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
                        }
                      }
                      break;
                  case /* Float */2 :
                      var a$23 = a$21._0;
                      if (typeof b$15 === "number") {
                        r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
                      } else {
                        switch (b$15.TAG | 0) {
                          case /* Int */1 :
                              var b$18 = b$15._0;
                              r$2 = b$18 !== 0 ? Caml_int32.mod_(a$23 | 0, b$18) : Stdlib.failwith("Trying to modulo with 0 on right hand side.");
                              break;
                          case /* Float */2 :
                              var b$19 = b$15._0;
                              r$2 = b$19 !== 0 ? a$23 % b$19 | 0 : Stdlib.failwith("Trying to modulo with 0 on right hand side.");
                              break;
                          default:
                            r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
                        }
                      }
                      break;
                  default:
                    r$2 = Stdlib.failwith("Trying to modulo non numeric literals.");
                }
              }
              return add_output({
                          TAG: /* Int */1,
                          _0: r$2
                        }, state);
          case /* CONCAT */12 :
              var right$12 = i._2;
              var a$24 = eval_expression(state, left).output;
              var b$20 = eval_expression(state, right$12).output;
              if (typeof a$24 === "number" || !(a$24.TAG === /* String */0 && !(typeof b$20 === "number" || b$20.TAG !== /* String */0))) {
                return Stdlib.failwith("Trying to concat non string literals.");
              } else {
                return add_output({
                            TAG: /* String */0,
                            _0: a$24._0 + b$20._0
                          }, state);
              }
          case /* AND */13 :
              var right$13 = i._2;
              var a$25 = eval_expression(state, left).output;
              var b$21 = eval_expression(state, right$13).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: is_true(a$25) && is_true(b$21)
                        }, state);
          case /* OR */14 :
              var right$14 = i._2;
              var a$26 = eval_expression(state, left).output;
              var b$22 = eval_expression(state, right$14).output;
              return add_output({
                          TAG: /* Bool */3,
                          _0: is_true(a$26) || is_true(b$22)
                        }, state);
          case /* DOT_ACCESS */15 :
              var right$15 = i._2;
              var left$1 = eval_expression(state, left).output;
              if (typeof left$1 === "number") {
                return add_output(/* Null */0, state);
              }
              switch (left$1.TAG | 0) {
                case /* Record */5 :
                    if (right$15.TAG !== /* LowercaseIdentifierExpression */9) {
                      return Stdlib.failwith("Expected right hand side of record access to be a lowercase identifier.");
                    }
                    var output = $$Option.value(Curry._2(Pinc_Ast.StringMap.find_opt, right$15._0._0, left$1._0), /* Null */0);
                    return add_output(output, state);
                case /* TemplateNode */8 :
                    if (right$15.TAG !== /* LowercaseIdentifierExpression */9) {
                      return Stdlib.failwith("I am really not sure what you are trying to do here...");
                    }
                    var b$23 = right$15._0._0;
                    switch (b$23) {
                      case "attributes" :
                          return add_output({
                                      TAG: /* Record */5,
                                      _0: left$1._2
                                    }, state);
                      case "children" :
                          return add_output({
                                      TAG: /* Array */4,
                                      _0: $$Array.of_list(left$1._3)
                                    }, state);
                      case "tag" :
                          return add_output({
                                      TAG: /* String */0,
                                      _0: left$1._1
                                    }, state);
                      default:
                        return Stdlib.failwith("Unknown property " + (b$23 + " on template node. Known properties are: `tag`, `attributes` and `children`."));
                    }
                default:
                  if (right$15.TAG === /* LowercaseIdentifierExpression */9) {
                    return Stdlib.failwith("Trying to access a property on a non record or template value.");
                  } else {
                    return Stdlib.failwith("I am really not sure what you are trying to do here...");
                  }
              }
          case /* BRACKET_ACCESS */16 :
              var right$16 = i._2;
              var left$2 = eval_expression(state, left).output;
              var right$17 = eval_expression(state, right$16).output;
              if (typeof left$2 === "number") {
                return add_output(/* Null */0, state);
              }
              switch (left$2.TAG | 0) {
                case /* Array */4 :
                    if (typeof right$17 === "number") {
                      return Stdlib.failwith("Cannot access array with a non integer value.");
                    }
                    if (right$17.TAG !== /* Int */1) {
                      return Stdlib.failwith("Cannot access array with a non integer value.");
                    }
                    var output$1;
                    try {
                      output$1 = Caml_array.get(left$2._0, right$17._0);
                    }
                    catch (raw_exn){
                      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                      if (exn.RE_EXN_ID === Stdlib.Invalid_argument) {
                        output$1 = /* Null */0;
                      } else {
                        throw exn;
                      }
                    }
                    return add_output(output$1, state);
                case /* Record */5 :
                    if (typeof right$17 === "number") {
                      return Stdlib.failwith("Cannot access record with a non string value.");
                    }
                    if (right$17.TAG !== /* String */0) {
                      return Stdlib.failwith("Cannot access record with a non string value.");
                    }
                    var output$2 = $$Option.value(Curry._2(Pinc_Ast.StringMap.find_opt, right$17._0, left$2._0), /* Null */0);
                    return add_output(output$2, state);
                default:
                  return Stdlib.failwith("Trying to access a property on a non record or array value.");
              }
          case /* FUNCTION_CALL */17 :
              return eval_function_call(state, {
                          hd: i._2,
                          tl: /* [] */0
                        }, left);
          case /* PIPE */18 :
              var right$18 = i._2;
              var right$19;
              right$19 = right$18.TAG === /* FunctionCall */7 ? ({
                    TAG: /* FunctionCall */7,
                    _0: right$18._0,
                    _1: {
                      hd: left,
                      tl: right$18._1
                    }
                  }) : ({
                    TAG: /* FunctionCall */7,
                    _0: right$18,
                    _1: {
                      hd: left,
                      tl: /* [] */0
                    }
                  });
              return eval_expression(state, right$19);
          case /* ARRAY_ADD */19 :
              var right$20 = i._2;
              var left$3 = eval_expression(state, left).output;
              var right$21 = eval_expression(state, right$20).output;
              if (typeof left$3 === "number" || left$3.TAG !== /* Array */4) {
                return Stdlib.failwith("Trying to add an element on a non array value.");
              } else {
                return add_output({
                            TAG: /* Array */4,
                            _0: $$Array.append(left$3._0, [right$21])
                          }, state);
              }
          case /* MERGE */20 :
              var right$22 = i._2;
              var left$4 = eval_expression(state, left).output;
              var right$23 = eval_expression(state, right$22).output;
              if (typeof left$4 !== "number") {
                switch (left$4.TAG | 0) {
                  case /* Array */4 :
                      if (typeof right$23 === "number" || right$23.TAG !== /* Array */4) {
                        return Stdlib.failwith("Trying to merge a non array value onto an array.");
                      } else {
                        return add_output({
                                    TAG: /* Array */4,
                                    _0: $$Array.append(left$4._0, right$23._0)
                                  }, state);
                      }
                  case /* Record */5 :
                      if (typeof right$23 === "number") {
                        return Stdlib.failwith("Trying to merge two non array values.");
                      }
                      switch (right$23.TAG | 0) {
                        case /* Array */4 :
                            break;
                        case /* Record */5 :
                            return add_output({
                                        TAG: /* Record */5,
                                        _0: Curry._3(Pinc_Ast.StringMap.merge, (function (param, x, y) {
                                                if (x !== undefined) {
                                                  if (y !== undefined) {
                                                    return y;
                                                  } else {
                                                    return x;
                                                  }
                                                } else if (y !== undefined) {
                                                  return y;
                                                } else {
                                                  return ;
                                                }
                                              }), left$4._0, right$23._0)
                                      }, state);
                        default:
                          return Stdlib.failwith("Trying to merge two non array values.");
                      }
                      break;
                  case /* TemplateNode */8 :
                      if (typeof right$23 === "number") {
                        return Stdlib.failwith("Trying to merge a non record value onto tag attributes.");
                      }
                      if (right$23.TAG !== /* Record */5) {
                        return Stdlib.failwith("Trying to merge a non record value onto tag attributes.");
                      }
                      var attributes = Curry._3(Pinc_Ast.StringMap.merge, (function (param, x, y) {
                              if (x !== undefined) {
                                if (y !== undefined) {
                                  return y;
                                } else {
                                  return x;
                                }
                              } else if (y !== undefined) {
                                return y;
                              } else {
                                return ;
                              }
                            }), left$4._2, right$23._0);
                      return add_output({
                                  TAG: /* TemplateNode */8,
                                  _0: left$4._0,
                                  _1: left$4._1,
                                  _2: attributes,
                                  _3: left$4._3,
                                  _4: left$4._4
                                }, state);
                  default:
                    
                }
              }
              if (typeof right$23 === "number" || right$23.TAG !== /* Array */4) {
                return Stdlib.failwith("Trying to merge two non array values.");
              } else {
                return Stdlib.failwith("Trying to merge an array value onto a non array.");
              }
          case /* RANGE */21 :
              return eval_range(state, false, left, i._2);
          case /* INCLUSIVE_RANGE */22 :
              return eval_range(state, true, left, i._2);
          
        }
    
  }
}

function eval_function_call(state, $$arguments, left) {
  var maybe_fn = eval_expression(state, left).output;
  if (typeof maybe_fn === "number") {
    return Stdlib.failwith("Trying to call a non function value");
  }
  if (maybe_fn.TAG !== /* Function */6) {
    return Stdlib.failwith("Trying to call a non function value");
  }
  var parameters = maybe_fn.parameters;
  if (List.compare_lengths(parameters, $$arguments) === 0) {
    var $$arguments$1 = List.fold_left((function (acc, param) {
            var value = eval_expression(state, param[1]).output;
            return Curry._3(Pinc_Ast.StringMap.add, param[0], value, acc);
          }), Pinc_Ast.StringMap.empty, List.combine(parameters, $$arguments));
    return add_output(Curry._3(maybe_fn.exec, $$arguments$1, maybe_fn.state, undefined), state);
  }
  if (List.compare_lengths(parameters, $$arguments) <= 0) {
    return Stdlib.failwith("This function only accepts " + (String(List.length(parameters)) + (" arguments, but was provided " + (String(List.length($$arguments)) + " here."))));
  }
  var arguments_len = List.length($$arguments);
  var missing = $$String.concat(", ", List.map((function (item) {
              return "`" + (item + "`");
            }), List.filteri((function (index, param) {
                  return index > (arguments_len - 1 | 0);
                }), parameters)));
  return Stdlib.failwith("This function was provided too few arguments. The following parameters are missing: " + missing);
}

function eval_let(state, ident, is_mutable, is_optional, expression) {
  var state$1 = eval_expression({
        binding_identifier: ident,
        models: state.models,
        slotted_children: state.slotted_children,
        declarations: state.declarations,
        context: state.context,
        output: state.output,
        environment: state.environment
      }, expression);
  var value = state$1.output;
  if (typeof value === "number" && !is_optional) {
    return Stdlib.failwith("identifier " + (ident + " is not marked as nullable, but was given a null value."));
  }
  return add_output(/* Null */0, add_value_to_scope(ident, value, is_optional, is_mutable, state$1));
}

function eval_range(state, inclusive, from, upto) {
  var from$1 = eval_expression(state, from).output;
  var upto$1 = eval_expression(state, upto).output;
  var match;
  var exit = 0;
  if (typeof from$1 === "number" || from$1.TAG !== /* Int */1) {
    exit = 1;
  } else {
    match = typeof upto$1 === "number" || upto$1.TAG !== /* Int */1 ? Stdlib.failwith("Can't construct range in for loop. The end of your range is not of type int.") : [
        from$1._0,
        upto$1._0
      ];
  }
  if (exit === 1) {
    match = typeof upto$1 === "number" || upto$1.TAG !== /* Int */1 ? Stdlib.failwith("Can't construct range in for loop. The start and end of your range are not of type int.") : Stdlib.failwith("Can't construct range in for loop. The start of your range is not of type int.");
  }
  var upto$2 = match[1];
  var from$2 = match[0];
  var iter;
  if (from$2 > upto$2) {
    iter = [];
  } else {
    var stop = inclusive ? upto$2 + 1 | 0 : upto$2;
    iter = $$Array.init(stop - from$2 | 0, (function (i) {
            return {
                    TAG: /* Int */1,
                    _0: i + from$2 | 0
                  };
          }));
  }
  return add_output({
              TAG: /* Array */4,
              _0: iter
            }, state);
}

function eval_block(state, statements) {
  var state$1 = add_scope(state);
  return List.fold_left((function (state) {
                return function (param) {
                  return eval_statement(state, param);
                };
              }), state$1, statements);
}

function eval_tag(value, state, tag) {
  var apply_default_value = function ($$default, value) {
    if ($$default !== undefined && typeof value === "number") {
      return eval_expression(state, $$default).output;
    } else {
      return value;
    }
  };
  var apply_transformer = function (transformer, value) {
    if (transformer === undefined) {
      return value;
    }
    var state$1 = add_value_to_scope(transformer[0]._0, value, false, false, add_scope(state));
    return eval_expression(state$1, transformer[1]).output;
  };
  var get_key = function (attributes) {
    var key = $$Option.map(get_output, $$Option.map((function (param) {
                return eval_expression(state, param);
              }), Curry._2(Pinc_Ast.StringMap.find_opt, "key", attributes)));
    var match = state.binding_identifier;
    if (key !== undefined) {
      if (typeof key === "number" || key.TAG !== /* String */0) {
        return Stdlib.failwith("Expected attribute `key` on tag to be of type string");
      } else {
        return key._0;
      }
    } else if (match !== undefined) {
      return match;
    } else {
      return Stdlib.failwith("Expected attribute `key` to exist on tag");
    }
  };
  var get_value = function (key) {
    if (value !== undefined) {
      return value;
    } else {
      return $$Option.value(Curry._1(state.models, key), /* Null */0);
    }
  };
  var tag_name = tag.tag_name;
  switch (tag_name) {
    case "Array" :
        var attributes = tag.attributes;
        var $$default = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes);
        var t = $$Option.map((function (t) {
                if (t.TAG === /* TagExpression */10) {
                  return t._0;
                } else {
                  return Stdlib.failwith("Expected attribute `of` to on #Array to be a tag, describing the type of the items of the array.");
                }
              }), Curry._2(Pinc_Ast.StringMap.find_opt, "of", attributes));
        var of$p = t !== undefined ? t : Stdlib.failwith("Expected attribute `of` to be present on #Array.");
        var key = get_key(attributes);
        var value$1 = get_value(key);
        var l = apply_default_value($$default, value$1);
        if (typeof l === "number") {
          return add_output(/* Null */0, state);
        }
        switch (l.TAG | 0) {
          case /* String */0 :
              return Stdlib.failwith("tried to assign string value to a array tag.");
          case /* Int */1 :
              return Stdlib.failwith("tried to assign int value to a array tag.");
          case /* Float */2 :
              return Stdlib.failwith("tried to assign float value to a array tag.");
          case /* Bool */3 :
              return Stdlib.failwith("tried to assign boolean value to a array tag.");
          case /* Array */4 :
              var eval_item = function (item) {
                return eval_tag(item, state, of$p);
              };
              var value$2 = apply_transformer(tag.transformer, {
                    TAG: /* Array */4,
                    _0: $$Array.map((function (it) {
                            return eval_item(it).output;
                          }), l._0)
                  });
              return add_output(value$2, state);
          case /* Record */5 :
              return Stdlib.failwith("tried to assign record value to a array tag.");
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a array tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a array tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a array tag.");
          
        }
    case "Boolean" :
        var transformer = tag.transformer;
        var attributes$1 = tag.attributes;
        var $$default$1 = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes$1);
        var key$1 = get_key(attributes$1);
        var value$3 = get_value(key$1);
        var b = apply_default_value($$default$1, value$3);
        if (typeof b === "number") {
          return add_output(apply_transformer(transformer, /* Null */0), state);
        }
        switch (b.TAG | 0) {
          case /* String */0 :
              return Stdlib.failwith("tried to assign string value to a boolean tag.");
          case /* Int */1 :
              return Stdlib.failwith("tried to assign int value to a boolean tag.");
          case /* Float */2 :
              return Stdlib.failwith("tried to assign float value to a boolean tag.");
          case /* Bool */3 :
              return add_output(apply_transformer(transformer, {
                              TAG: /* Bool */3,
                              _0: b._0
                            }), state);
          case /* Array */4 :
              return Stdlib.failwith("tried to assign array value to a boolean tag.");
          case /* Record */5 :
              return Stdlib.failwith("tried to assign record value to a boolean tag.");
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a boolean tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a boolean tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a boolean tag.");
          
        }
    case "Float" :
        var transformer$1 = tag.transformer;
        var attributes$2 = tag.attributes;
        var $$default$2 = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes$2);
        var key$2 = get_key(attributes$2);
        var value$4 = get_value(key$2);
        var f = apply_default_value($$default$2, value$4);
        if (typeof f === "number") {
          return add_output(apply_transformer(transformer$1, /* Null */0), state);
        }
        switch (f.TAG | 0) {
          case /* String */0 :
              return Stdlib.failwith("tried to assign string value to a float tag.");
          case /* Int */1 :
              return Stdlib.failwith("tried to assign int value to a float tag.");
          case /* Float */2 :
              return add_output(apply_transformer(transformer$1, {
                              TAG: /* Float */2,
                              _0: f._0
                            }), state);
          case /* Bool */3 :
              return Stdlib.failwith("tried to assign boolean value to a float tag.");
          case /* Array */4 :
              return Stdlib.failwith("tried to assign array value to a float tag.");
          case /* Record */5 :
              return Stdlib.failwith("tried to assign record value to a float tag.");
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a float tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a float tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a float tag.");
          
        }
    case "GetContext" :
        var attributes$3 = tag.attributes;
        var $$default$3 = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes$3);
        var name = Curry._2(Pinc_Ast.StringMap.find_opt, "name", attributes$3);
        var s = eval_expression(state, name !== undefined ? name : Stdlib.failwith("attribute name is required when getting a context.")).output;
        var name$1;
        name$1 = typeof s === "number" || s.TAG !== /* String */0 ? Stdlib.failwith("Expected attribute `name` on #Context to be of type string.") : s._0;
        var value$5 = apply_default_value($$default$3, $$Option.value(get_context(name$1, state), /* Null */0));
        return add_output(apply_transformer(tag.transformer, value$5), state);
    case "Int" :
        var transformer$2 = tag.transformer;
        var attributes$4 = tag.attributes;
        var $$default$4 = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes$4);
        var key$3 = get_key(attributes$4);
        var value$6 = get_value(key$3);
        var i = apply_default_value($$default$4, value$6);
        if (typeof i === "number") {
          return add_output(apply_transformer(transformer$2, /* Null */0), state);
        }
        switch (i.TAG | 0) {
          case /* String */0 :
              return Stdlib.failwith("tried to assign string value to a int tag.");
          case /* Int */1 :
              return add_output(apply_transformer(transformer$2, {
                              TAG: /* Int */1,
                              _0: i._0
                            }), state);
          case /* Float */2 :
              return Stdlib.failwith("tried to assign float value to a int tag.");
          case /* Bool */3 :
              return Stdlib.failwith("tried to assign boolean value to a int tag.");
          case /* Array */4 :
              return Stdlib.failwith("tried to assign array value to a int tag.");
          case /* Record */5 :
              return Stdlib.failwith("tried to assign record value to a int tag.");
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a int tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a int tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a int tag.");
          
        }
    case "Record" :
        var attributes$5 = tag.attributes;
        var expr = Curry._2(Pinc_Ast.StringMap.find_opt, "of", attributes$5);
        var of$p$1 = expr !== undefined ? expr : Stdlib.failwith("Expected attribute `of` to be present on #Record.");
        var key$4 = get_key(attributes$5);
        var value$7 = get_value(key$4);
        if (typeof value$7 === "number") {
          return add_output(/* Null */0, state);
        }
        switch (value$7.TAG | 0) {
          case /* String */0 :
              return Stdlib.failwith("tried to assign string value to a record tag.");
          case /* Int */1 :
              return Stdlib.failwith("tried to assign int value to a record tag.");
          case /* Float */2 :
              return Stdlib.failwith("tried to assign float value to a record tag.");
          case /* Bool */3 :
              return Stdlib.failwith("tried to assign boolean value to a record tag.");
          case /* Array */4 :
              return Stdlib.failwith("tried to assign array value to a record tag.");
          case /* Record */5 :
              var r = value$7._0;
              var models = function (key) {
                return Curry._2(Pinc_Ast.StringMap.find_opt, key, r);
              };
              var r$1 = eval_expression({
                    binding_identifier: state.binding_identifier,
                    models: models,
                    slotted_children: state.slotted_children,
                    declarations: state.declarations,
                    context: state.context,
                    output: state.output,
                    environment: state.environment
                  }, of$p$1).output;
              if (typeof r$1 === "number" || r$1.TAG !== /* Record */5) {
                return Stdlib.failwith("Expected attribute `of` to on #Record to be a record, describing the shape the items inside.");
              } else {
                return add_output(apply_transformer(tag.transformer, r$1), state);
              }
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a record tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a record tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a record tag.");
          
        }
    case "SetContext" :
        if (tag.transformer !== undefined) {
          return Stdlib.failwith("Unknown tag with name `" + (tag_name + "`."));
        }
        var attributes$6 = tag.attributes;
        var name$2 = Curry._2(Pinc_Ast.StringMap.find_opt, "name", attributes$6);
        var s$1 = eval_expression(state, name$2 !== undefined ? name$2 : Stdlib.failwith("attribute name is required when setting a context.")).output;
        var name$3;
        name$3 = typeof s$1 === "number" || s$1.TAG !== /* String */0 ? Stdlib.failwith("Expected attribute `name` on >#Context to be of type string.") : s$1._0;
        var value$8 = Curry._2(Pinc_Ast.StringMap.find_opt, "value", attributes$6);
        var value$9 = eval_expression(state, value$8 !== undefined ? value$8 : Stdlib.failwith("attribute value is required when setting a context.")).output;
        return add_output(/* Null */0, add_context(name$3, value$9, state));
    case "Slot" :
        var attributes$7 = tag.attributes;
        var s$2 = $$Option.value($$Option.map(get_output, $$Option.map((function (param) {
                        return eval_expression(state, param);
                      }), Curry._2(Pinc_Ast.StringMap.find_opt, "name", attributes$7))), {
              TAG: /* String */0,
              _0: ""
            });
        var slot_name;
        slot_name = typeof s$2 === "number" || s$2.TAG !== /* String */0 ? Stdlib.failwith("Expected attribute `name` on #Slot to be of type string.") : s$2._0;
        var i$1 = $$Option.value($$Option.map(get_output, $$Option.map((function (param) {
                        return eval_expression(state, param);
                      }), Curry._2(Pinc_Ast.StringMap.find_opt, "min", attributes$7))), {
              TAG: /* Int */1,
              _0: 0
            });
        var min;
        min = typeof i$1 === "number" || i$1.TAG !== /* Int */1 ? Stdlib.failwith("Expected attribute `min` on #Slot to be of type int.") : i$1._0;
        var param = $$Option.map(get_output, $$Option.map((function (param) {
                    return eval_expression(state, param);
                  }), Curry._2(Pinc_Ast.StringMap.find_opt, "max", attributes$7)));
        var max = param !== undefined ? (
            typeof param === "number" || param.TAG !== /* Int */1 ? Stdlib.failwith("Expected attribute `max` on #Slot to be of type int.") : param._0
          ) : undefined;
        var param$1 = $$Option.map(get_output, $$Option.map((function (param) {
                    return eval_expression(state, param);
                  }), Curry._2(Pinc_Ast.StringMap.find_opt, "instanceOf", attributes$7)));
        var instanceOf = param$1 !== undefined ? (
            typeof param$1 === "number" || param$1.TAG !== /* Array */4 ? Stdlib.failwith("Expected attribute `instanceOf` on #Slot to be an array.") : $$Array.map((function (info) {
                      if (typeof info === "number" || info.TAG !== /* DefinitionInfo */7) {
                        return Stdlib.failwith("Expected attribute `instanceOf` on #Slot to be an array of uppercase identifiers.");
                      } else {
                        return info._0;
                      }
                    }), param$1._0)
          ) : undefined;
        var children = state.slotted_children;
        if (children === undefined) {
          return add_output(/* Null */0, state);
        }
        var find_slot_key = function (attributes) {
          var s = $$Option.value(Curry._2(Pinc_Ast.StringMap.find_opt, "slot", attributes), {
                TAG: /* String */0,
                _0: ""
              });
          if (typeof s === "number" || s.TAG !== /* String */0) {
            return Stdlib.failwith("Expected slot attribute to be of type string");
          } else {
            return s._0;
          }
        };
        var keep_slotted = function (acc, value) {
          if (typeof value === "number") {
            return Stdlib.failwith("Only nodes may be placed into slots. If you want to put a plain text into a slot, you have to wrap it in a <p></p> tag for example.");
          }
          switch (value.TAG | 0) {
            case /* String */0 :
                if ($$String.trim(value._0) === "") {
                  return acc;
                } else {
                  return Stdlib.failwith("Only nodes may be placed into slots. If you want to put a plain text into a slot, you have to wrap it in a <p></p> tag for example.");
                }
            case /* Array */4 :
                return $$Array.fold_left(keep_slotted, acc, value._0);
            case /* TemplateNode */8 :
                if (find_slot_key(value._2) === slot_name) {
                  var tag = value._1;
                  var f = $$Array.append(acc, [value]);
                  if (instanceOf === undefined) {
                    return f;
                  }
                  var is_in_list = {
                    contents: false
                  };
                  var match = List.partition_map((function (param) {
                          var name = param.name;
                          if (name === tag) {
                            is_in_list.contents = true;
                          }
                          if (param.negated) {
                            return Either.right(name);
                          } else {
                            return Either.left(name);
                          }
                        }), $$Array.to_list(instanceOf));
                  var allowed = match[0];
                  var is_in_list$1 = is_in_list.contents;
                  var is_allowed = allowed ? (
                      match[1] ? List.mem(tag, allowed) : is_in_list$1
                    ) : !is_in_list$1;
                  if (is_allowed) {
                    return f;
                  }
                  var arg = [];
                  return Stdlib.failwith("Child with tag `" + (tag + ("` may not be used inside the " + ((
                                    slot_name === "" ? "Default #Slot." : "#Slot with name `" + (slot_name + "`")
                                  ) + (". The following restrictions are set: [ " + ($$String.concat(",", List.map((function (res) {
                                                  return (
                                                          res.negated ? "!" : ""
                                                        ) + res.name;
                                                }), $$Array.to_list((function (param) {
                                                        return $$Option.value(param, arg);
                                                      })(instanceOf)))) + " ]"))))));
                } else {
                  return acc;
                }
            default:
              return Stdlib.failwith("Only nodes may be placed into slots. If you want to put a plain text into a slot, you have to wrap it in a <p></p> tag for example.");
          }
        };
        var slotted_children = $$Array.fold_left(keep_slotted, [], $$Array.of_list(children));
        var slotted_children$1 = apply_transformer(tag.transformer, {
              TAG: /* Array */4,
              _0: slotted_children
            });
        var amount_of_children;
        if (typeof slotted_children$1 === "number") {
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "Pinc_Interpreter.ml",
                  1339,
                  15
                ],
                Error: new Error()
              };
        }
        if (slotted_children$1.TAG === /* Array */4) {
          amount_of_children = slotted_children$1._0.length;
        } else {
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "Pinc_Interpreter.ml",
                  1339,
                  15
                ],
                Error: new Error()
              };
        }
        var exit = 0;
        if (slot_name === "") {
          if (amount_of_children < min) {
            return Stdlib.failwith("Default #Slot did not reach the minimum amount of nodes (specified as " + (String(min) + ")."));
          }
          exit = 2;
        } else {
          exit = 2;
        }
        if (exit === 2) {
          if (amount_of_children < min) {
            return Stdlib.failwith("#Slot with name `" + (slot_name + ("` did not reach the minimum amount of nodes (specified as " + (String(min) + ")."))));
          }
          if (slot_name === "") {
            if (max === undefined) {
              return add_output(slotted_children$1, state);
            }
            if (amount_of_children > max) {
              return Stdlib.failwith("Default #Slot includes more than the maximum amount of nodes (specified as " + (String(max) + ")."));
            }
            
          }
          
        }
        if (max !== undefined && amount_of_children > max) {
          return Stdlib.failwith("#Slot with name `" + (slot_name + ("` includes more than the maximum amount of nodes (specified as " + (String(max) + ")."))));
        } else {
          return add_output(slotted_children$1, state);
        }
        break;
    case "String" :
        var transformer$3 = tag.transformer;
        var attributes$8 = tag.attributes;
        var $$default$5 = Curry._2(Pinc_Ast.StringMap.find_opt, "default", attributes$8);
        var key$5 = get_key(attributes$8);
        var value$10 = get_value(key$5);
        var s$3 = apply_default_value($$default$5, value$10);
        if (typeof s$3 === "number") {
          return add_output(apply_transformer(transformer$3, /* Null */0), state);
        }
        switch (s$3.TAG | 0) {
          case /* String */0 :
              return add_output(apply_transformer(transformer$3, {
                              TAG: /* String */0,
                              _0: s$3._0
                            }), state);
          case /* Int */1 :
              return Stdlib.failwith("tried to assign integer value to a string tag.");
          case /* Float */2 :
              return Stdlib.failwith("tried to assign float value to a string tag.");
          case /* Bool */3 :
              return Stdlib.failwith("tried to assign boolean value to a string tag.");
          case /* Array */4 :
              return Stdlib.failwith("tried to assign array value to a string tag.");
          case /* Record */5 :
              return Stdlib.failwith("tried to assign record value to a string tag.");
          case /* Function */6 :
              return Stdlib.failwith("tried to assign function to a string tag.");
          case /* DefinitionInfo */7 :
              return Stdlib.failwith("tried to assign definition info to a string tag.");
          case /* TemplateNode */8 :
              return Stdlib.failwith("tried to assign template node to a string tag.");
          
        }
    default:
      return Stdlib.failwith("Unknown tag with name `" + (tag_name + "`."));
  }
}

function eval_template(state, template) {
  switch (template.TAG | 0) {
    case /* HtmlTemplateNode */0 :
        var attributes = Curry._2(Pinc_Ast.StringMap.map, get_output, Curry._2(Pinc_Ast.StringMap.map, (function (param) {
                    return eval_expression(state, param);
                  }), template.attributes));
        var children = List.map(get_output, List.map((function (param) {
                    return eval_template(state, param);
                  }), template.children));
        return add_output({
                    TAG: /* TemplateNode */8,
                    _0: "Html",
                    _1: template.tag,
                    _2: attributes,
                    _3: children,
                    _4: template.self_closing
                  }, state);
    case /* ComponentTemplateNode */1 :
        var tag = template.identifier._0;
        var attributes$1 = Curry._2(Pinc_Ast.StringMap.map, get_output, Curry._2(Pinc_Ast.StringMap.map, (function (param) {
                    return eval_expression(state, param);
                  }), template.attributes));
        var children$1 = List.map(get_output, List.map((function (param) {
                    return eval_template(state, param);
                  }), template.children));
        var render_fn = function (models, slotted_children) {
          return $$eval(models, slotted_children, Caml_option.some(state.context), tag, state.declarations).output;
        };
        return add_output({
                    TAG: /* TemplateNode */8,
                    _0: {
                      NAME: "Component",
                      VAL: render_fn
                    },
                    _1: tag,
                    _2: attributes$1,
                    _3: children$1,
                    _4: false
                  }, state);
    case /* ExpressionTemplateNode */2 :
        return eval_expression(state, template._0);
    case /* TextTemplateNode */3 :
        return add_output({
                    TAG: /* String */0,
                    _0: template._0
                  }, state);
    
  }
}

function $$eval(models, slotted_children, context, root, declarations) {
  var state = make(models, slotted_children, context, declarations);
  var declaration = Curry._2(Pinc_Ast.StringMap.find_opt, root, declarations);
  if (declaration !== undefined) {
    return eval_block(state, declaration._1);
  } else {
    return Stdlib.failwith("Declaration with name `" + (root + "` was not found."));
  }
}

function from_source(models, slotted_children, filenameOpt, source, root) {
  var filename = filenameOpt !== undefined ? filenameOpt : "";
  var declarations = Pinc_Parser.parse(filename, source);
  return $$eval(models, slotted_children, undefined, root, declarations);
}

var Value = {
  to_string: to_string,
  $$null: $$null,
  of_string: of_string,
  of_bool: of_bool,
  of_int: of_int,
  of_float: of_float,
  of_list: of_list,
  of_string_map: of_string_map,
  make_component: make_component
};

var State = {
  get_output: get_output,
  get_bindings: get_bindings
};

export {
  Value ,
  State ,
  $$eval ,
  from_source ,
}
/* Float Not a pure module */
