// Generated by Melange

import * as $$Array from "melange/lib/es6/array.js";

var void_elements = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr"
];

function is_void_el(s) {
  return $$Array.mem(s, void_elements);
}

export {
  is_void_el ,
}
/* No side effect */
