// Generated by Melange

import * as Marshal from "melange/lib/es6/marshal.js";
import * as Caml_external_polyfill from "melange/lib/es6/caml_external_polyfill.js";

var SourceLocation = {};

function marshal(d) {
  return Caml_external_polyfill.resolve("caml_output_value_to_string")(d, /* [] */0);
}

function unmarshal(s) {
  return Marshal.from_string(s, 0);
}

var Declaration = {
  marshal: marshal,
  unmarshal: unmarshal
};

export {
  SourceLocation ,
  Declaration ,
}
/* No side effect */
