// Generated by Melange


function make(filename, line, column) {
  return {
          filename: filename,
          line: line,
          column: column
        };
}

export {
  make ,
}
/* No side effect */
