// Generated by Melange

import * as $$Map from "bs-platform/lib/es6/map.js";
import * as $$String from "bs-platform/lib/es6/string.js";

var StringMap = $$Map.Make({
      compare: $$String.compare
    });

var SourceLocation = {};

export {
  StringMap ,
  SourceLocation ,
}
/* StringMap Not a pure module */
