// Generated by Melange

import * as $$Map from "bs-platform/lib/es6/map.js";
import * as $$String from "bs-platform/lib/es6/string.js";

var include = $$Map.Make({
      compare: $$String.compare
    });

var empty = include.empty;

var is_empty = include.is_empty;

var mem = include.mem;

var add = include.add;

var update = include.update;

var singleton = include.singleton;

var remove = include.remove;

var merge = include.merge;

var union = include.union;

var compare = include.compare;

var equal = include.equal;

var iter = include.iter;

var fold = include.fold;

var for_all = include.for_all;

var exists = include.exists;

var filter = include.filter;

var filter_map = include.filter_map;

var partition = include.partition;

var cardinal = include.cardinal;

var bindings = include.bindings;

var min_binding = include.min_binding;

var min_binding_opt = include.min_binding_opt;

var max_binding = include.max_binding;

var max_binding_opt = include.max_binding_opt;

var choose = include.choose;

var choose_opt = include.choose_opt;

var split = include.split;

var find = include.find;

var find_opt = include.find_opt;

var find_first = include.find_first;

var find_first_opt = include.find_first_opt;

var find_last = include.find_last;

var find_last_opt = include.find_last_opt;

var map = include.map;

var mapi = include.mapi;

var to_seq = include.to_seq;

var to_rev_seq = include.to_rev_seq;

var to_seq_from = include.to_seq_from;

var add_seq = include.add_seq;

var of_seq = include.of_seq;

export {
  empty ,
  is_empty ,
  mem ,
  add ,
  update ,
  singleton ,
  remove ,
  merge ,
  union ,
  compare ,
  equal ,
  iter ,
  fold ,
  for_all ,
  exists ,
  filter ,
  filter_map ,
  partition ,
  cardinal ,
  bindings ,
  min_binding ,
  min_binding_opt ,
  max_binding ,
  max_binding_opt ,
  choose ,
  choose_opt ,
  split ,
  find ,
  find_opt ,
  find_first ,
  find_first_opt ,
  find_last ,
  find_last_opt ,
  map ,
  mapi ,
  to_seq ,
  to_rev_seq ,
  to_seq_from ,
  add_seq ,
  of_seq ,
}
/* include Not a pure module */
