site Default {
  request = @Context(name: request)

  language =
    @NodeContext(name: language, options: [
      @ContextOption(value: "de_DE", condition: request.uri|split("/")|index(1) == "de"),
      @ContextOption(value: "en_GB", fallbacks: ["de_DE"], condition: request.uri|split("/")|index(1) == "en"),
      @ContextOption(value: "en_US", fallbacks: ["en_GB", "de_DE"], condition: request.uri|split("/")|index(1) == "gb"),
    ])
    @Default("de_DE")
}
